// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQoOsJqK57RVgr72zpWWF4l1hQUHdrLs',
    appId: '1:387883646801:web:8aab7464beffd8a10f5d70',
    messagingSenderId: '387883646801',
    projectId: 'record-bcace',
    authDomain: 'record-bcace.firebaseapp.com',
    storageBucket: 'record-bcace.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_k8Qvv-5mm077s6VRgyq__YUAx8yVkU8',
    appId: '1:387883646801:android:3f0c66dff0c853830f5d70',
    messagingSenderId: '387883646801',
    projectId: 'record-bcace',
    storageBucket: 'record-bcace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg1KGewrFdu0c3U9zWRPhYiNLNbfQcpSg',
    appId: '1:387883646801:ios:dff5cac0088e57250f5d70',
    messagingSenderId: '387883646801',
    projectId: 'record-bcace',
    storageBucket: 'record-bcace.appspot.com',
    iosBundleId: 'com.example.record',
  );
}
